kind: pipeline
name: default

platform:
  os: linux

matrix:
  arch: arm64

steps:
- name: powershell
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quamotion/powershell
    tags: arm64
    dockerfile: powershell/Dockerfile

- name: xcuitrunner
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quamotion/xcuitrunner
    tags: arm64
    dockerfile: xcuitrunner/Dockerfile

- name: webdriver
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quamotion/webdriver
    tags: arm64
    dockerfile: webdriver/Dockerfile
