sudo: required

services:
  - docker

env:
  - WEBDRIVER_VERSION=0.103.12

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - echo Packaging Quamotion WebDriver $WEBDRIVER_VERSION
  - docker --version
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/webdriver:$WEBDRIVER_VERSION webdriver
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/webdriver:$WEBDRIVER_VERSION-bionic webdriver-bionic
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/webdriver:$WEBDRIVER_VERSION-tools webdriver-tools
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/powershell:$WEBDRIVER_VERSION powershell
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/powershell:$WEBDRIVER_VERSION-bionic powershell-bionic
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/xcuitrunner:$WEBDRIVER_VERSION xcuitrunner
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/xcuitrunner:$WEBDRIVER_VERSION-bionic xcuitrunner-bionic
  
  - echo Starting webdriver to determine the version
  - docker run --net host -d --name webdriver quamotion/webdriver:$WEBDRIVER_VERSION
  - while ! nc -z localhost 17894; do sleep 1; echo -n '.'; done
  - quamotion_version=`curl localhost:17894/wd/hub/status | jq .value.build.fileVersion -r | sed 's/\.[^.]*$//'`
  - docker stop webdriver
  - echo Building for Quamotion v$quamotion_version
  
  - docker tag quamotion/webdriver:$WEBDRIVER_VERSION quamotion/webdriver:latest
  - docker tag quamotion/powershell:$WEBDRIVER_VERSION quamotion/powershell:latest
  - docker tag quamotion/xcuitrunner:$WEBDRIVER_VERSION quamotion/xcuitrunner:latest
  - docker tag quamotion/webdriver:$WEBDRIVER_VERSION-bionic quamotion/webdriver:latest-bionic
  - docker tag quamotion/powershell:$WEBDRIVER_VERSION-bionic quamotion/powershell:latest-bionic
  - docker tag quamotion/xcuitrunner:$WEBDRIVER_VERSION-bionic quamotion/xcuitrunner:latest-bionic

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  
  - docker push quamotion/webdriver:$WEBDRIVER_VERSION
  - docker push quamotion/webdriver:$WEBDRIVER_VERSION-bionic
  - docker push quamotion/webdriver:$WEBDRIVER_VERSION-tools
  - docker push quamotion/powershell:$WEBDRIVER_VERSION
  - docker push quamotion/powershell:$WEBDRIVER_VERSION-bionic
  - docker push quamotion/xcuitrunner:$WEBDRIVER_VERSION
  - docker push quamotion/xcuitrunner:$WEBDRIVER_VERSION-bionic
  
  - docker push quamotion/webdriver:latest
  - docker push quamotion/powershell:latest
  - docker push quamotion/xcuitrunner:latest
  - docker push quamotion/webdriver:latest-bionic
  - docker push quamotion/powershell:latest-bionic
  - docker push quamotion/xcuitrunner:latest-bionic
