sudo: required

services:
  - docker

env:
  - WEBDRIVER_VERSION=0.91.75

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - echo Packaging Quamotion WebDriver $WEBDRIVER_VERSION
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/ubuntu:$TRAVIS_BUILD_NUMBER ubuntu
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/webdriver:$TRAVIS_BUILD_NUMBER webdriver
  - docker build --build-arg WEBDRIVER_VERSION=$WEBDRIVER_VERSION -t quamotion/powershell:$TRAVIS_BUILD_NUMBER powershell
  
  - echo Starting webdriver to determine the version
  - docker run --net host -d --name webdriver quamotion/webdriver:$TRAVIS_BUILD_NUMBER
  - while ! nc -z localhost 17894; do sleep 1; echo -n '.'; done
  - quamotion_version=`curl localhost:17894/wd/hub/status | jq .value.build.fileVersion -r | sed 's/\.[^.]*$//'`
  - docker stop webdriver
  - echo Building for Quamotion v$quamotion_version
  
  - docker build -t quamotion/ubuntu:$quamotion_version ubuntu
  - docker build -t quamotion/webdriver:$quamotion_version webdriver
  - docker build -t quamotion/powershell:$quamotion_version powershell
  
  - docker build -t quamotion/ubuntu:latest ubuntu
  - docker build -t quamotion/webdriver:latest webdriver
  - docker build -t quamotion/powershell:latest powershell

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  
  - docker push quamotion/ubuntu:$quamotion_version
  - docker push quamotion/webdriver:$quamotion_version
  - docker push quamotion/powershell:$quamotion_version
  
  - docker push quamotion/ubuntu:latest
  - docker push quamotion/webdriver:latest
  - docker push quamotion/powershell:latest
