sudo: required

services:
  - docker

script:
  - docker build -t quamotion/jenkins-slave jenkins-slave:$TRAVIS_BUILD_NUMBER

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSW"
  - docker push quamotion/jenkins-slave:$TRAVIS_BUILD_NUMBER